var WEB_APP_URL = 'https://script.google.com/macros/s/AKfycbw5GRH9tyiEWigMF-EPdGq4-OoEuA4yeQ9PsSYHiO5GW7Wjy9si749aj0I0ra0ufw0/exec';

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// 動画タスクデータ（Claude が更新）
var BAKED_DATA = [
  {
    "id": "成田ch_65",
    "pubDate": "5/11",
    "title": "物販で売上1億いくまでに大事なこと（スモビジ）",
    "shootDate": "4/22",
    "handoverDate": "4/24",
    "handoverDone": "",
    "editor": "熊谷",
    "draftDate": "4/29",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=1932961521&range=A66",
    "sheetName": "成田ch",
    "editorStatus": "済",
    "proofDeadline": "5/11",
    "revisionDeadline": "5/10",
    "notes": "受領＋限定公開済"
  },
  {
    "id": "Yoshi ch_136",
    "pubDate": "5/14",
    "title": "YC ローマロエベ",
    "shootDate": "イタリア",
    "handoverDate": "4/2",
    "handoverDone": "",
    "editor": "谷添さん",
    "draftDate": "5/6",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=706953571&range=A137",
    "sheetName": "Yoshi ch",
    "editorStatus": "修正稿",
    "proofDeadline": "5/11",
    "revisionDeadline": "",
    "notes": "修正は伏見対応"
  },
  {
    "id": "成田ch_66",
    "pubDate": "5/18",
    "title": "実践者インタ木村さん",
    "shootDate": "3/16",
    "handoverDate": "済み",
    "handoverDone": "",
    "editor": "木下",
    "draftDate": "4/29",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=1932961521&range=A67",
    "sheetName": "成田ch",
    "editorStatus": "修正稿",
    "proofDeadline": "5/11",
    "revisionDeadline": "5/14",
    "notes": "修正稿受領"
  },
  {
    "id": "Yoshi ch_137",
    "pubDate": "5/22",
    "title": "ブランド品転売ビジネスなら無在庫も簡単。",
    "shootDate": "4/17",
    "handoverDate": "4/23",
    "handoverDone": "",
    "editor": "谷添さん",
    "draftDate": "5/14",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=706953571&range=A138",
    "sheetName": "Yoshi ch",
    "editorStatus": "初稿待ち",
    "proofDeadline": "",
    "revisionDeadline": "",
    "notes": ""
  },
  {
    "id": "成田ch_67",
    "pubDate": "5/24",
    "title": "騙されるな転売ビジネスもう稼げない",
    "shootDate": "4/22",
    "handoverDate": "4/24",
    "handoverDone": "",
    "editor": "上原",
    "draftDate": "5/6",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=1932961521&range=A68",
    "sheetName": "成田ch",
    "editorStatus": "初稿",
    "proofDeadline": "5/12",
    "revisionDeadline": "5/17",
    "notes": "5/12中に必ず"
  },
  {
    "id": "成田ch_68",
    "pubDate": "6/1",
    "title": "1000万稼ぎたいならクラファンが一番",
    "shootDate": "4/22",
    "handoverDate": "4/24",
    "handoverDone": "",
    "editor": "熊谷 （予定）",
    "draftDate": "5/25",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=1932961521&range=A69",
    "sheetName": "成田ch",
    "editorStatus": "依頼済み",
    "proofDeadline": "",
    "revisionDeadline": "",
    "notes": ""
  },
  {
    "id": "成田ch_69",
    "pubDate": "6/7",
    "title": "2026年最新スモビジ",
    "shootDate": "4/22",
    "handoverDate": "4/24",
    "handoverDone": "",
    "editor": "熊谷 （予定）",
    "draftDate": "6/1",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=1932961521&range=A70",
    "sheetName": "成田ch",
    "editorStatus": "依頼済み",
    "proofDeadline": "",
    "revisionDeadline": "",
    "notes": ""
  },
  {
    "id": "船原ch_113",
    "pubDate": "7/5",
    "title": "差別化ローンチLINE",
    "shootDate": "5/25",
    "handoverDate": "",
    "handoverDone": "",
    "editor": "",
    "draftDate": "",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=1260224820&range=A114",
    "sheetName": "船原ch",
    "editorStatus": "引き継ぎ待ち",
    "proofDeadline": "",
    "revisionDeadline": "",
    "notes": ""
  },
  {
    "id": "船原ch_115",
    "pubDate": "7/17",
    "title": "BUYMAローンチLINE",
    "shootDate": "6/5",
    "handoverDate": "",
    "handoverDone": "",
    "editor": "",
    "draftDate": "",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=1260224820&range=A116",
    "sheetName": "船原ch",
    "editorStatus": "引き継ぎ待ち",
    "proofDeadline": "",
    "revisionDeadline": "",
    "notes": ""
  },
  {
    "id": "船原ch_117",
    "pubDate": "7/29",
    "title": "（座学）仕事を辞めたい40代50代見ないと損しますLINE",
    "shootDate": "4/10",
    "handoverDate": "4/13",
    "handoverDone": "",
    "editor": "加藤",
    "draftDate": "4/26",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=1260224820&range=A118",
    "sheetName": "船原ch",
    "editorStatus": "修正稿",
    "proofDeadline": "5/8",
    "revisionDeadline": "5/10",
    "notes": "格納待ち"
  },
  {
    "id": "Yoshi ch_146",
    "pubDate": "ストック",
    "title": "re極貧生活",
    "shootDate": "",
    "handoverDate": "",
    "handoverDone": "",
    "editor": "北川さん",
    "draftDate": "済？",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=706953571&range=A147",
    "sheetName": "Yoshi ch",
    "editorStatus": "格納済",
    "proofDeadline": "",
    "revisionDeadline": "",
    "notes": "企画D確認待ち"
  },
  {
    "id": "Yoshi ch_147",
    "pubDate": "ストック",
    "title": "YCローマFENDI",
    "shootDate": "イタリア",
    "handoverDate": "3/31",
    "handoverDone": "",
    "editor": "",
    "draftDate": "",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=706953571&range=A148",
    "sheetName": "Yoshi ch",
    "editorStatus": "",
    "proofDeadline": "",
    "revisionDeadline": "",
    "notes": "谷添さんに依頼したい"
  },
  {
    "id": "Yoshi ch_151",
    "pubDate": "ストック",
    "title": "免税手続き・改",
    "shootDate": "3/10",
    "handoverDate": "4/23",
    "handoverDone": "",
    "editor": "谷添 （予定）",
    "draftDate": "",
    "sheetUrl": "https://docs.google.com/spreadsheets/d/1VswrYvsGmY7hKLXwIjh9cptVHqhwthCiy5hatLvn-A4/edit#gid=706953571&range=A152",
    "sheetName": "Yoshi ch",
    "editorStatus": "",
    "proofDeadline": "",
    "revisionDeadline": "",
    "notes": "谷添さんに依頼したい"
  }
];

// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// その他タスクデータ（Claude が更新）
// { id, title, deadline, category, status, notes, createdDate }
// status: 未着手 / 対応中 / 待ち / 完了
// category: 連絡 / 確認 / 作業 / 企画 / その他
var OTHER_TASKS = [
  {
    "id": "other_001",
    "title": "Slack添削①",
    "url": "https://fmclub.slack.com/archives/C08EHBETT17/p1778475024607399?thread_ts=1778474885.789889&cid=C08EHBETT17",
    "deadline": "",
    "category": "作業",
    "status": "未着手",
    "notes": "",
    "createdDate": "5/11"
  },
  {
    "id": "other_002",
    "title": "Slack添削②",
    "url": "https://fmclub.slack.com/archives/C08EHBETT17/p1778459993173289?thread_ts=1777536681.905599&cid=C08EHBETT17",
    "deadline": "",
    "category": "作業",
    "status": "未着手",
    "notes": "",
    "createdDate": "5/11"
  }
];
